# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @import RcppArmadillo
NULL

GenerateMatrixC <- function(K_B, p) {
    .Call('_SA23204160_GenerateMatrixC', PACKAGE = 'SA23204160', K_B, p)
}

